[application]
name = "scrow"
default_platform = "web"

[web.app]
title = "Satoshi Escrow"
base_path = "scrow"

[web.resource]
# Copy all assets to the output directory
style = ["./assets/tailwind.css"]
# Include all files from assets directory
dir = ["./assets"]

[web.resource.dev]
style = ["./assets/tailwind.css"]
dir = ["./assets"]
