[application]
name = "scrow"
default_platform = "web"

[web.app]
base_path = "/scrow/"
title = "AGORA Escrow"

[web.resource]
base_path = "/scrow/"
# Disable service worker for security
service_worker = false

[bundle]
identifier = "com.escrow.agora"
