[application]
name = "scrow"
default_platform = "web"

[web.app]
title = "Satoshi Escrow"
base_path = "scrow"

[web.resource]
style = ["./assets/tailwind.css"]

[web.resource.dev]
style = ["./assets/tailwind.css"]
