name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Tailwind CSS CLI
      run: |
        curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
        chmod +x tailwindcss-linux-x64
        sudo mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

    - name: Build Tailwind CSS
      run: tailwindcss -i ./input.css -o ./assets/tailwind.css --minify

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Dioxus CLI
      run: cargo install dioxus-cli

    - name: Build Dioxus App (Release)
      run: dx build --release

    - name: Debug - List dist contents
      run: |
        echo "Contents of dist directory:"
        ls -la ./dist/
        echo "Contents of dist subdirectories:"
        find ./dist/ -type f -name "*.html" -o -name "*.js" -o -name "*.wasm" | head -10

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
